//
//  RemindersListModels.swift
//  Fahad Test
//
//  Created by Mac on 21/11/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum RemindersList {
    
  // MARK: Use cases
    enum GetList {
        struct Request {}
        struct Response {
            var items: [ListModel]?
            var error: AppError?
        }
        struct ViewModel {
            var items: [ListModel]?
            var error: AppError?
        }
    }
}
