//
//  RemindersListPresenter.swift
//  Fahad Test
//
//  Created by Mac on 21/11/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RemindersListPresentationLogic {
    func presentList(response: RemindersList.GetList.Response)
    func presentLocalList()
}

class RemindersListPresenter: Presenter, RemindersListPresentationLogic {
    
    weak var viewControllerRemindersList: RemindersListDisplayLogic? {
        return viewController as? RemindersListDisplayLogic
    }
    
    func presentList(response: RemindersList.GetList.Response) {
        let viewModel = RemindersList.GetList.ViewModel(items: response.items, error: response.error)
        viewControllerRemindersList?.displayList(viewModel: viewModel)
    }
    
    func presentLocalList() {
        viewControllerRemindersList?.displayLocalList()
    }
}
