//
//  RemindersListWorker.swift
//  Fahad Test
//
//  Created by Mac on 21/11/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

class RemindersListWorker {
    func doFetchList(request: RemindersList.GetList.Request, completionHandler: @escaping([ListModel]?, AppError?) -> Void) {
        let endPoint = MainEndPoints.getList(request: request)
        do {
            let request = try endPoint.asURLRequest()
            Request.sharedInstance.makeRequet(request: request, dataReturnType: [ListModel].self) { (response) in
                switch response {
                case .success(let genericObject):
                    completionHandler(genericObject, nil)
                case .failure(let error):
                    print("Error Occured: \(error)")
                    completionHandler(nil, error)
                }
            }
        } catch {
            completionHandler(nil, AppError.internalFailed(reason: error))
        }
    }
}
