//
//  ReminderDetailPresenter.swift
//  Fahad Test
//
//  Created by Mac on 21/11/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ReminderDetailPresentationLogic {}

class ReminderDetailPresenter: Presenter, ReminderDetailPresentationLogic {
    
    weak var viewControllerReminderDetail: ReminderDetailDisplayLogic? {
        return viewController as? ReminderDetailDisplayLogic
    }
}
